name: Build

on:
  push:
    branches:
      - '*'
    paths:
      - .github/workflows/build.yml
      - cloudy/**/*
      - Makefile
      - requirements.txt
      - setup.py

jobs:
  Linux:
    runs-on: ubuntu-20.04
    container: python:3.12-alpine

    steps:
      - uses: actions/checkout@v2
      - name: Build prep
        id: build_prep
        run: |
          apk add --no-cache make
          echo "version=$(echo ${GITHUB_SHA} | cut -c1-8)" >> "$GITHUB_ENV"
      - name: Build binary
        run: |
          make build_static
          dist/static/cloudy --version
      - name: Run CLI tests
        run: |
          dist/static/cloudy test
      - name: Generate tarball
        run: |
          make pack_static BUILD_VERSION=${{ env.version }}
      - name: Upload tarball
        uses: actions/upload-artifact@v1
        with:
          name: cloudy-${{ env.version }}-linux-x86_64.tar.gz
          path: pack/cloudy-${{ env.version }}-linux-x86_64.tar.gz
      - name: Upload checksum
        uses: actions/upload-artifact@v1
        with:
          name: cloudy-${{ env.version }}-linux-x86_64.sha256sum
          path: pack/cloudy-${{ env.version }}-linux-x86_64.sha256sum
