name: Build

on:
  push:
    branches:
      - '*'
    paths:
      - .github/workflows/build.yml
      - cloudy/**/*
      - Makefile
      - requirements.txt
      - setup.py

jobs:
  Linux:
    runs-on: ubuntu-20.04
    container: python:3.11-alpine

    steps:
      - uses: actions/checkout@v2
      - name: Get build version
        id: build_version
        run: |
          echo ::set-output name=version::$(echo ${GITHUB_SHA} | cut -c1-8)
      - name: Build release
        run: |
          make build_static
          dist/static/cloudy --version
          make pack_static BUILD_VERSION=${{ steps.build_version.outputs.version }}
      - name: Upload release file
        uses: actions/upload-artifact@v1
        with:
          name: cloudy-${{ steps.build_version.outputs.version }}-linux-x86_64.tar.gz
          path: pack/cloudy-${{ steps.build_version.outputs.version }}-linux-x86_64.tar.gz
      - name: Upload checksum file
        uses: actions/upload-artifact@v1
        with:
          name: cloudy-${{ steps.build_version.outputs.version }}-linux-x86_64.sha256sum
          path: pack/cloudy-${{ steps.build_version.outputs.version }}-linux-x86_64.sha256sum
